### ISSUE TITLE
I guess EAT project is available on only Windows?

### ISSUE THREAD

**Issue by ryukato** [nhnent/eat#9]
I saw some path values working on only Windows such as "C:\Users\". So I guess it's better replace such path values to work with on other OS.

**Comment by JiseongKim** [comment]
Thank you @ryukato , But it not true.
I guess you might be see it on example `config.json`, there are some configuration values to easy understand meaning.
But if not, could you leave code. (it should be changed)

**Comment by JiseongKim** [comment]
Hi @ryukato 
I remove useless code in the pom.xml
Could you review the code which a Pull Requested?

**Comment by ryukato** [comment]
LGTM, I can compile and install the projects. 
But I need to look at more deeper and run the example scenarios.
Anyway, this PR is looking good. 

Thanks,
